name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install swiftformat
        brew install yamllint

    - name: Run SwiftFormat
      run: swiftformat . --lint

    - name: Run YAML lint
      run: yamllint .cursorscratchpad

    - name: Build project
      run: swift build --build-tests --parallel

    - name: Run tests
      run: swift test --parallel 