name: Tuna CI

on:
  push:
    branches: [ main, 'feature/**', 'bugfix/**', 'release/**', 'infra-**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1

    - name: Install CI dependencies
      run: |
        chmod +x Scripts/ci-setup.sh
        ./Scripts/ci-setup.sh

    - name: Bootstrap environment
      run: make bootstrap

    - name: Lint code
      run: make lint

    - name: Run snapshot tests
      run: make snapshot
      continue-on-error: true  # 允许快照测试失败，但我们仍然会上传差异

    - name: Run tests
      run: make test

    - name: Upload snapshot diff artifacts
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: snapshot-diffs
        path: Tests/Snapshots/__FailureDiffs__
        if-no-files-found: ignore 