name: CI

on:
  push:
    branches: [ main, dev-* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: swift-actions/setup-swift@v1

    - name: Detect duplicate producers
      run: |
        swift package diagnose 2>&1 | grep -q "multiple producers" && {
          echo "::error::duplicate sources detected"
          exit 1
        } || true

    - name: Build and test
      run: |
        swift build --build-tests
        swift test 